[package]
name = "top-repos"
version = "0.1.0"
edition = "2018"
license = "MIT"
description = "THINGY"
authors = ["Will Lane <williamlane923@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
regex = "1.5.4"
threadpool = "1.8.1"
